// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdAqVyEqqFfjezN8JUKbHdl_uL8qu1ZvU',
    appId: '1:138926593882:web:2cb6b7d8f67c8dd0500563',
    messagingSenderId: '138926593882',
    projectId: 'sironi1',
    authDomain: 'sironi1.firebaseapp.com',
    databaseURL: 'https://sironi1-default-rtdb.firebaseio.com',
    storageBucket: 'sironi1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDta49rDF04REQMEkprJRiHSO2hYiuXyAM',
    appId: '1:138926593882:android:e6dad4fada48d0c9500563',
    messagingSenderId: '138926593882',
    projectId: 'sironi1',
    databaseURL: 'https://sironi1-default-rtdb.firebaseio.com',
    storageBucket: 'sironi1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyYUVHmHCGnuaF99zEp5Yuh4wRtqkbpZg',
    appId: '1:138926593882:ios:77d7c78acbf3d1e6500563',
    messagingSenderId: '138926593882',
    projectId: 'sironi1',
    databaseURL: 'https://sironi1-default-rtdb.firebaseio.com',
    storageBucket: 'sironi1.appspot.com',
    iosBundleId: 'com.example.sironi1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyYUVHmHCGnuaF99zEp5Yuh4wRtqkbpZg',
    appId: '1:138926593882:ios:77d7c78acbf3d1e6500563',
    messagingSenderId: '138926593882',
    projectId: 'sironi1',
    databaseURL: 'https://sironi1-default-rtdb.firebaseio.com',
    storageBucket: 'sironi1.appspot.com',
    iosBundleId: 'com.example.sironi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdAqVyEqqFfjezN8JUKbHdl_uL8qu1ZvU',
    appId: '1:138926593882:web:caed448c47617db2500563',
    messagingSenderId: '138926593882',
    projectId: 'sironi1',
    authDomain: 'sironi1.firebaseapp.com',
    databaseURL: 'https://sironi1-default-rtdb.firebaseio.com',
    storageBucket: 'sironi1.appspot.com',
  );
}
